/*CREATE DATABASE consorcio_2019_22;*/
USE consorcio_2019_22;
CREATE TABLE tb_laboratorio (
COD_LAB INT PRIMARY KEY auto_increment,
DES_LAB VARCHAR (50)

)ENGINE= INNODB;

CREATE TABLE tb_distrito(
COD_DS INT PRIMARY KEY auto_increment,
NOM_DIS VARCHAR(45)

)ENGINE= INNODB;

CREATE TABLE tb_empleado(
COD_EMP INT PRIMARY KEY auto_increment,
NOM_EMP VARCHAR (30),
APE_EMP VARCHAR (30),
SEX_EMP VARCHAR (15),
FEC_REG_EMP DATE,
FEC_NAC_EMP DATE,
DIR_EMP VARCHAR (30),
COD_DIS_EMP INT,

FOREIGN KEY (COD_DIS_EMP) REFERENCES tb_distrito(COD_DS) 
ON UPDATE CASCADE ON DELETE CASCADE 

)ENGINE= INNODB;

CREATE TABLE tb_cliente (
COD_CLI INT PRIMARY KEY auto_increment,
NOM_CLI VARCHAR (30),
APE_CLI VARCHAR (30),
SEX_CLI VARCHAR (15),
FEC_REG_CLI DATE,
DIR_CLI VARCHAR (30),
COD_DIS_CLI INT,

FOREIGN KEY (COD_DIS_CLI) REFERENCES tb_distrito(COD_DS) 
ON UPDATE CASCADE ON DELETE CASCADE 

)ENGINE= INNODB;


CREATE TABLE tb_medicamento(
COD_MED INT PRIMARY KEY auto_increment,
NOM_MED VARCHAR (50),
COD_LAB INT,
STOCK_MED INT,
PRE_MED DOUBLE,
FEC_VEN_MED DATE,

FOREIGN KEY (COD_LAB) REFERENCES tb_laboratorio(COD_LAB) 
ON UPDATE CASCADE ON DELETE CASCADE 

)ENGINE= INNODB;


CREATE TABLE tb_boleta(
NUM_BOL INT PRIMARY KEY auto_increment,
COD_CLI INT,
COD_EMP INT,
FEC_EMI_BOL DATE,
MONTO_BOL DECIMAL (10,0),

FOREIGN KEY (COD_CLI) REFERENCES tb_cliente(COD_CLI) 
ON UPDATE CASCADE ON DELETE CASCADE,

FOREIGN KEY (COD_EMP) REFERENCES tb_empleado(COD_EMP) 
ON UPDATE CASCADE ON DELETE CASCADE 


)ENGINE= INNODB;



CREATE TABLE tb_medicamento_boleta(
NUM_BOL INT,
COD_MED INT,
CANT INT,

FOREIGN KEY (NUM_BOL) REFERENCES tb_boleta(NUM_BOL) 
ON UPDATE CASCADE ON DELETE CASCADE, 

FOREIGN KEY (COD_MED) REFERENCES tb_medicamento(COD_MED) 
ON UPDATE CASCADE ON DELETE CASCADE 

)ENGINE= INNODB;

INSERT INTO tb_laboratorio VALUES(null,'Laboratorio1');
INSERT INTO tb_laboratorio VALUES(NULL,'Laboratorio2');

INSERT INTO tb_medicamento VALUES(null,'aaa111',1,44,4,'2010-02-02');
INSERT INTO tb_medicamento VALUES(null,'aaa222',1,44,4,'2010-02-02');

INSERT INTO tb_distrito VALUES(null,'Rimac');
INSERT INTO tb_distrito VALUES(null,'SJL');